# https://taskfile.dev

version: "3"

dotenv: [".env"]

tasks:
  run-all-test:
    desc: "运行全部测试"
    #    deps: [init-windows-venv]
    cmd: pytest -q --alluredir reports/allure_results

  run-fail-test:
    desc: "仅运行失败的测试用例"
    cmd: pytest --lf --alluredir reports/allure_results

  install:
    desc: "安装项目依赖包"
    cmd: pip install -r requirements.txt

  show-repost:
    desc: "查看测试报告"
    cmd: allure serve reports/allure_results/

  init-windows-venv:
    desc: "venv环境初始化"
    platforms: [windows]
    cmds:
      - pwsh .venv/Scripts/activate.ps1
    silent: true
