# https://taskfile.dev

version: '3'

dotenv: ['.env']

tasks:
  run-all-test:
    desc: '运行全部测试'
    cmd: pytest -n auto --alluredir reports/allure_results

  run-fail-test:
    desc: '仅运行失败的测试用例'
    cmd: pytest --lf --alluredir reports/allure_results

  run-test:
    cmd: pytest testcases/api/api_test/test.py -vv

  install:
    desc: '安装项目依赖包'
    cmds:
      - uv venv
      - uv sync
      - task: playwright-install

  show-report:
    desc: '查看测试报告'
    cmd: allure serve reports/allure_results/

  playwright-codegen:
    desc: '生成playwright测试代码'
    cmd: playwright codegen $BASE_URL

  playwright-install:
    desc: '安装playwright依赖'
    cmd: playwright install chromium
